# Generated by Django 4.2.7 on 2023-12-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revuCMS', '0002_category_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='imageUrl',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
