# Generated by Django 4.2.7 on 2024-01-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revuCMS', '0008_user_firstname_user_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastName',
        ),
    ]
