# Generated by Django 4.2.7 on 2024-01-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revuCMS', '0011_answerchoice_question_quiz_userresponse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='number_of_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='required_score_to_pass',
            field=models.IntegerField(blank=True, help_text='required score in %', null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.PositiveIntegerField(help_text='duration of the quiz in minutes'),
        ),
    ]
