# Generated by Django 4.2.7 on 2024-01-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revuCMS', '0012_remove_question_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
