# Generated by Django 4.2.7 on 2024-01-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revuCMS', '0013_alter_quiz_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=6)),
            ],
        ),
    ]
