# Generated by Django 4.2.7 on 2024-01-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revuCMS', '0016_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
