# Generated by Django 5.0 on 2024-02-02 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revuCMS', '0018_alter_quizattempt_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='quiz_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revuCMS.quizattempt'),
        ),
    ]
