# Generated by Django 5.0 on 2024-02-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revuCMS', '0021_badge_award_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
