# Generated by Django 5.0 on 2024-02-02 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revuCMS', '0023_alter_badge_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='image',
        ),
    ]
